services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
    image: naveensainijpr/whatwebuild_admin_panel:latest
    container_name: whatwebuild_admin_panel
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
